version: '2'

services:
  packet-forwarder:
    build: ./hm-pktfwd
    depends_on:
      - helium-miner
    restart: always
    privileged: true
    volumes:
      - pktfwdr:/var/pktfwd
    environment:
      - FIRMWARE_VERSION=v1.0.0-alpha.21

  helium-miner:
    build: ./hm-gatewayrs
    privileged: true
    expose:
      - "1680"
    ports:
      - "44158:44158/tcp"
    volumes:
      - miner-storage:/var/data
      - miner-log:/var/log/miner
      - pktfwdr:/var/pktfwd
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/i2c-1:/dev/i2c-1
    restart: on-failure
    environment:
      - RELEASE_BUMPER=foobar
      - FIRMWARE_VERSION=v1.0.0-alpha.21
    labels:
      io.balena.features.balena-api: '1'

volumes:
  miner-storage:
  miner-log:
  pktfwdr:
